services:
  postgres:
    image: postgres:17

    container_name: quantora-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: quantora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: